# Column names used through data.table's non-standard evaluation.
utils::globalVariables(c(
  ".", "..cols", "active", "active_label", "attribute_count",
  "attribute_scan_label", "authors", "bbox_area_proxy", "bbox_available",
  "bbox_native", "bbox_pane", "bbox_size_class", "bbox_status", "bbox_wgs84",
  "cell_size_x", "cell_size_y", "citation_date", "citation_key",
  "classification_source", "classified_by_name", "comparison_class",
  "component_modtime_latest", "component_modtime_latest_chr", "content_hint",
  "crs_auth_code", "crs_input", "crs_status", "current", "current_record",
  "dashboard_order", "data_file_description", "data_file_extension",
  "data_file_format", "data_file_notes", "data_file_rel_path_full",
  "data_file_rel_path_save", "dataset", "dataset_path", "description",
  "display_format", "display_modified_time", "display_name", "display_path",
  "display_role", "display_size_kb", "display_title", "document_dir",
  "document_name", "document_rel_path", "document_type_auto_text",
  "document_type_label", "document_type_user_set", "document_type_user_text",
  "east", "eligibility_message", "eligibility_status", "eligible",
  "extent_label", "extent_scope", "field", "field_code", "file_dir",
  "file_name", "file_name_save", "file_path", "file_path_save", "file_role",
  "file_size_kb", "file_stem", "group_key", "id", "include",
  "include_in_attribute_scan", "include_in_dataset_bbox",
  "include_in_lineage", "include_in_lineage_label", "include_in_metadata",
  "include_in_metadata_label", "inclusion", "is_advanced", "is_container",
  "is_selected", "item", "label", "last_seen_at",
  "latest_attribute_profile_at", "layer_count", "layer_name", "legend_field",
  "license_identifier", "lifecycle_label", "lifecycle_stage_mismatch",
  "lifecycle_status", "linked_source", "lock_display", "logical_dir",
  "logical_extension", "logical_file_name", "logical_file_path",
  "logical_file_role", "logical_format", "logical_rel_path",
  "logical_size_bytes", "logical_size_kb", "logical_size_mb", "logical_stem",
  "metadata_readiness", "metadata_section", "metadata_status",
  "mismatch_display", "missing_fields", "missing_since", "modified_time",
  "modtime", "next_action", "normalized_file_path", "north", "notes",
  "obligation", "organisation_address", "organisation_code",
  "organisation_name_full", "organisation_name_short", "overview_class",
  "path_key", "pond_location", "Primary dataset", "primary_dataset",
  "profile_check", "profile_completed_at", "profile_date", "profile_message",
  "profile_status", "profiled_by_name", "proposed", "raster_res_x",
  "raster_res_y", "readiness_display", "ready_for_archive", "record_status",
  "rectangle_opacity", "required_missing", "resolved_file_path",
  "review_status", "review_timestamp", "reviewed_by_name", "reviewer_role",
  "role", "role_normalised", "role_rank", "row_class", "saved_records",
  "scan_status", "section", "sidecar_summary", "size", "sort_group",
  "sort_name", "sort_order", "source_crs", "source_id", "source_key",
  "source_label", "source_note", "source_of_change", "source_type", "south",
  "spatial_extent", "spatial_note", "stage", "stage_display", "status",
  "subtab", "tab", "title", "title_display", "type", "ui_group",
  "update_reason", "update_summary", "update_type", "updated_at",
  "updated_by_name", "west", "xmax", "xmin", "ymax", "ymin"
))
